### ISSUE TITLE
Customcheck result data is ignored by server (maybe special character escape problem)

### ISSUE THREAD

**Issue by exa-mk** [it-novum/openitcockpit-agent-go#52] opened 2021-06-07 07:53 UTC
**Agent Mode**:
* [] Pull Model (openITCOCKPIT Server request data from Agent)
* [x] Push Model (Agent send data to openITCOCKPIT)

**Versions**
* openITCOKPIT Server Version: 4.2.1
* openITCOCKPIT Monitoring Agent Version: 3.0.2

**Operating system**
Server: Ubuntu 20.04
Agent: CentOS, Fedora

* Do you use an HTTP proxy? no
* Are you using Auto-TLS, HTTPS or HTTP? https
* Used CPU architecture: amd64

**Describe the bug**
I have some agent custom checks that include path names in the check identifier. After the upgrade from agent 1.x to 3.x I recognized these are now escaped by a \\ before each path seperator /. I fixed the check names within the server but they still don't seem to be recognized:

Check output:
![grafik](https://user-images.githubusercontent.com/69202794/120978728-1279b800-c775-11eb-9381-9f7d16e3305c.png)

Agent push data:
```
[...]
    "customchecks": {
        "check_megaraid_sas": {
            "stdout": "OK: 0:0:RAID-1:2 drives:465.25GB:Optimal 0:1:RAID-6:24 drives:371.5GB:Optimal Drives:26 \n",
            "rc": 0,
            "execution_unix_timestamp_sec": 1623051310
        },
        "check_systemtime": {
            "stdout": "LEAP STATUS OK - System clock is in sync. | leap_status=0;0;2;;2 root_deviation=0.0059870385;0;;;\n",
            "rc": 0,
            "execution_unix_timestamp_sec": 1623051310
        },
        "nfs_io__\/nfs\/home": {
            "stdout": "NFS I\/O OK:  on all shares. [Mount points: \/nfs\/home]|'fs04.dev.exasol.com:\/nfs\/home_r_avg_exe'=0ms;;;0; 'fs04.dev.exasol.com:\/nfs\/home_rkBs'=0KB;;;0; 'fs04.dev.exasol.com:\/nfs\/home_r_avg_rtt'=0ms;;;0; 'fs04.dev.exasol.com:\/nfs\/home_rs'=0;;;0; 'fs04.dev.exasol.com:\/nfs\/home_w_avg_exe'=0ms;;;0; 'fs04.dev.exasol.com:\/nfs\/home_wkBs'=0KB;;;0; 'fs04.dev.exasol.com:\/nfs\/home_w_avg_rtt'=0ms;;;0; 'fs04.dev.exasol.com:\/nfs\/home_ws'=0;;;0; \n",
            "rc": 0,
            "execution_unix_timestamp_sec": 1623051310
        },
[...]
```

Agent customcheck config:
```
[nfs_io__/nfs/home]
  command = /usr/lib/nagios/plugins/check_nfs_io.pl -a --include=/nfs/home 
  interval = 180
  timeout = 10
  enabled = True
```

**To Reproduce**
Include above customcheck config in agent and add service to monitoring.

**Expected behavior**
Service check result data is recognized properly. In best case I don't need to escape the customcheck name in the server at all.

**Screenshots**
see above

**Comment by nook24** [comment] 2021-06-07 08:54
I was unable to reproduce this issue. I tried PUSH and PULL mode. Both worked as expected.
Please do not add any escaping manually, it is not required! I would recommend to delete the service and recreate it again through the wizard.

My customchecks.ini:
```ini
[nfs_io__/nfs/home]
  command = /usr/bin/echo "This is the command nfs_io__/nfs/home"
  interval = 10
  timeout = 5
  enabled = True
```

Create Service:
![Bildschirmfoto 2021-06-07 um 10 18 41](https://user-images.githubusercontent.com/9019992/120987641-13631780-c77e-11eb-8de5-ca1111eff081.png)

Monitoring results:
![Bildschirmfoto 2021-06-07 um 10 19 19](https://user-images.githubusercontent.com/9019992/120987657-178f3500-c77e-11eb-8c91-ffbab1e82449.png)

My Service defenition:
![Bildschirmfoto 2021-06-07 um 10 38 17](https://user-images.githubusercontent.com/9019992/120987696-21189d00-c77e-11eb-8c92-55ae179539f5.png)


It is worth mentioning that the escaping is done by the JSON library and should be transparent to the end user

![Bildschirmfoto 2021-06-07 um 10 19 38](https://user-images.githubusercontent.com/9019992/120987723-2aa20500-c77e-11eb-817d-14d5d80e9b16.png)


```
root@1fa7afc81cda:/# php -v
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies


root@1fa7afc81cda:/# php -a
Interactive mode enabled

php > $test = ['nfs_io__/nfs/home' => 'data'];
php > $json = json_encode($test);
php > print_r($json);
{"nfs_io__\/nfs\/home":"data"}         // Has escaping in json
php > print_r(json_decode($json, true));
Array
(
    [nfs_io__/nfs/home] => data        // Escaping is gone as soon as JSON string got processed by PHP
)
php >
```

**Comment by exa-mk** [comment] 2021-06-07 09:12
Re-creating the check seems to work.
It's a bit stange a the checks don't look differently from before where they refused to work. That's why I tried to escape the path in the first time.

**Comment by nook24** [comment] 2021-06-07 09:22
Perfect, I'll close the issue. Feel free to reopen if you have any further issues.

**Closed** 2021-06-07 09:37 UTC
